### ISSUE TITLE
SyntaxError: can't use starred expression here

### ISSUE THREAD

**Issue by Jia-Bin** [je-suis-tm/machine-learning#30]
Environment: Python 3.10 + Numpy 1.23.1

When running  gaussian discriminant analysis.ipynb

"SyntaxError: can't use starred expression here" pop up

as below:

  Input In [2]
    *np.exp(
    ^
SyntaxError: can't use starred expression here

**Comment by je-suis-tm** [comment]
You are right, there is syntax error. It has been fixed. Just lose `\` between bracket and multiplication when I copy from spyder to jupyter. Thanks.
